name: Compile and Minify TypeScript

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.ts'
      - '!**/*.d.ts'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npx tsc

    - name: Minify JavaScript
      run: npm run minify:js

    - name: Commit minified JavaScript file
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add src/example.min.js
        git commit -m "Compiled TS and minified JS" || echo "No changes to commit"
        git push